### ISSUE TITLE
can not resolve pattern "/dev/disc/desc"

### ISSUE THREAD

**Issue by jerome-diver** [jcsp/smartmontools#1]
on archlinux, there is no /dev/discs/ directory
on openmediavault-arm, there is no /dev/discs/ drectory

then smartctl --scan failed

How to indicate smartmontool to search in the good place instead of /dev/discs/ ?
there is /dev/disk/[by-label,by-uuid,by-id,by-partlabel,by-partuuid,by-path]
I supposed to use a script or a config file, but i can not find any documentation for doing that.
Any help would be welcome.
thank you

**Comment by jcsp** [comment]
This is just a fork.  Report issues upstream at https://www.smartmontools.org/
